dbType: mysql
host: localhost
port: 3306
user: root
password: 123456
schema: boot
tables:
  - pms_sku
serviceName: boot
outFile: ./data/api/boot.api
jwt: true
middleware:
  - Auth
ignoreColumns: 
  - deleted_at 
  - version
  - mid
onlySearch:
  - id
  - created_at
  - updated_at
  - deleted_at