dbType: mysql
host: localhost
port: 3306
user: root
password: 123456
schema: boot
tables:
  - pms_brand
  - pms_category
  - pms_category_attribute
  - pms_goods
  - pms_goods_attribute
  - pms_sku
serviceName: pms
packageName: pms
goPackageName: ./pms
outFile: ./data/pd/pms.proto
ignoreTables:  
ignoreColumns: 
  - deleted_at 
  - version
onlySearch:
  - id
  - created_at
  - updated_at

